### ISSUE TITLE
Not showing?

### ISSUE THREAD

**Issue by eggbean** [phelipetls/jsonpath.nvim#5]
The winbar with the path doesn't show up for me. I have `nvim-treesitter` installed and `:script` shows that the `after/ftplugin/json.lua` file has loaded.

How else can I troubleshoot this?

**Comment by phelipetls** [comment]
Did you include the below snippet in `after/ftplugin/json.lua`?

```
if vim.fn.exists("+winbar") == 1 then
  vim.opt_local.winbar = "%{%v:lua.require'jsonpath'.get()%}"
end
```

This might be confusing, but the plugin does not change the winbar out of the box, it just exposes a function. I'm guessing this may be the problem.

**Comment by eggbean** [comment]
Thanks, but I just can't get it working, which is a pity, as I was hoping this could help me understand jq better.

I even tried using [vim-greprtpscr](https://github.com/jyscao/vim-greprtpscr) to see if it was loading and it appears that it is.

I do have an unusual setup though, where I change the XDG locations to `~/.config/vim` and the configuration is shared with 'vim' but this has not caused any problems with anything else. I am also using the appimage binary for nvim.

I will try without this change at some point. Cheers.

**Comment by phelipetls** [comment]
Sorry for this bad experience. Don't know exactly what's going on. Maybe try the oneliner below?

```
autocmd FileType json setlocal winbar=%{luaeval('require\"jsonpath\".get()')}
```

**Comment by eggbean** [comment]
Thanks, but that didn't work. I guess I am finally experiencing the consequences of having a complicated setup, as it's proving difficult to debug this.
